name: Publish to NPM
on: { workflow_call: { inputs: { artifact: { type: string, required: true } } } }
jobs:
  publish:
    name: Publish tree-sitter-recipe
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }
    environment: { name: npm, url: "${{ steps.meta.outputs.url }}" }
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6
        with: { node-version: latest, registry-url: https://registry.npmjs.org }
      - uses: actions/download-artifact@v8
        with: { name: "${{ inputs.artifact }}" }
      - id: meta
        run: echo "url=https://npm.im/package/$(yq -r .name package.json)/v/$(yq -r .version package.json)" >> "$GITHUB_OUTPUT"
      - run: bunx npm@latest publish --provenance --access public --ignore-scripts
